import { NgModule } from '@angular/core';
import { MatButtonModule, 
        MatIconModule, 
        MatToolbarModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatInputModule,
        MatCheckboxModule,
        MatSelectModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatDialogModule,
        MatCardModule,
        MatAutocompleteModule, 
        MatRadioModule, 
        MatTabsModule, 
        MatTableModule, 
        MatSortModule, 
        MatPaginatorModule, MatBadgeModule} from '@angular/material'
import { ReactiveFormsModule } from '@angular/forms';

@NgModule ({
    imports:[
        MatButtonModule,
        MatIconModule,
        MatToolbarModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatInputModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatDialogModule,
        MatCardModule,
        MatAutocompleteModule,
        ReactiveFormsModule,
        MatDialogModule,
        MatRadioModule,
        MatCheckboxModule,
        MatTabsModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatBadgeModule
    ],
    exports:[
        MatButtonModule,
        MatIconModule,
        MatToolbarModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatInputModule,
        MatCheckboxModule,
        MatSelectModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatDialogModule,
        MatCardModule,
        MatAutocompleteModule,
        ReactiveFormsModule,
        MatDialogModule,
        MatRadioModule,
        MatCheckboxModule,
        MatTabsModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule,
        MatBadgeModule
    ]
})

export class MaterialModule {}